# Exercice 1.1 : Fonction de moyenne

In [1]:
def calcul_moyenne(donnees: list[float]) -> float:
  

    return sum(donnees) / len(donnees)

In [2]:
calcul_moyenne([5.0, 3.0, 6.0])

4.666666666666667

# Exercice 1.2 : Gestion d’une liste vide

In [6]:
def calcul_moyenne(donnees: list[float]) -> float | None:
   
    if len(donnees) == 0:
        print( 'None')
        return None
        
    return sum(donnees) / len(donnees)

In [7]:
calcul_moyenne([])

None


In [9]:
def calcul_moyenne(donnees: list[float]) -> float | None:
   
    if not donnees:
        return None
        
    return sum(donnees) / len(donnees)

In [10]:
print(calcul_moyenne([]) )

None


# Exercice 1.3 : Analyse de données génomiques

In [11]:
def gene_plus_exprime(expressions: dict[str, int]) -> str | None:

    if not expressions:
        return None
        
    gene_max = None
    expression_max = float('-inf')
    
    for gene, niveau_gene in expressions.items():
        if niveau_gene > expression_max:
            gene_max = gene
            expression_max = niveau_gene
            
    return gene_max

**Test**

In [12]:
donnees = {"BRCA1": 5200, "TP53": 3400, "EGFR": 4100}
resultat = gene_plus_exprime(donnees)
print(resultat)

BRCA1


# Exercice 1.6 : Création de tenseurs de base

In [13]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [16]:
import tensorflow as tf

tensor_tf = tf.constant([[1, 2],
                         [3, 4]])

print(tensor_tf.shape)

(2, 2)


In [15]:
import torch

tensor_pt = torch.tensor([[1, 2],
                          [3, 4]])


print(tensor_pt.shape)

torch.Size([2, 2])


# Exercice 1.7 : Opérations tensoriels

In [22]:
import torch

# Création des tenseurs 3x3
a = torch.tensor([[1, 2, 3],
                  [1, 0, 1],
                  [9, 8, 7]], dtype=torch.float32)

b = torch.tensor([[2, 1, 3],
                  [6, 5, 4],
                  [3, 8, 1]], dtype=torch.float32)

# 1. Addition élément par élément
addition = a + b

# 2. Multiplication matricielle
matmul = torch.matmul(a, b)

# 3. Produit élément-wise (Hadamard)
hadamard = a * b

# Affichage des résultats
print("Tenseur a:\n", a)
print("\nTenseur b:\n", b)
print("\nAddition élément par élément:\n", addition)
print("\nMultiplication matricielle:\n", matmul)
print("\nProduit Hadamard:\n", hadamard)

Tenseur a:
 tensor([[1., 2., 3.],
        [1., 0., 1.],
        [9., 8., 7.]])

Tenseur b:
 tensor([[2., 1., 3.],
        [6., 5., 4.],
        [3., 8., 1.]])

Addition élément par élément:
 tensor([[ 3.,  3.,  6.],
        [ 7.,  5.,  5.],
        [12., 16.,  8.]])

Multiplication matricielle:
 tensor([[ 23.,  35.,  14.],
        [  5.,   9.,   4.],
        [ 87., 105.,  66.]])

Produit Hadamard:
 tensor([[ 2.,  2.,  9.],
        [ 6.,  0.,  4.],
        [27., 64.,  7.]])
